cargo-features = ["profile-rustflags"]

[package]
name = "zaychik"
version = "0.0.15"
edition = "2021"

[profile.release]
rustflags = ["-C", "strip=symbols"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
tokio = { version = "1.23.0", features = ["macros", "rt-multi-thread"] }
figment = { version = "0.10", features = ["toml", "env"] }
serde = { version = "1.0.149", features = ["derive"] }
poise = "0.5.1"
async-trait = "0.1.59"
rand = "0.8.5"
reqwest = { version = "0.11.13", features = ["json"] }
serde_json = "1.0.89"
anyhow = "1.0.66"
nanoid = "0.4.0"

[dependencies.serenity]
version = "0.11.5"
default-features = false
features = [
    "builder",
    "cache",
    "chrono",
    "collector",
    "client",
    "gateway",
    "http",
    "model",
    "utils",
    "rustls_backend",
]
