version: "3.3"

services:
  zaychik:
    image: eclipse-temurin:17-alpine
    container_name: zaychik
    restart: unless-stopped
    volumes:
      - type: bind
        source: ./
        target: /opt/app
    working_dir: /opt/app
    command: ['java', '-XX:+UseZGC', '-Xmx512M', '-jar', 'zaychik.jar']
