version: "3"

services:
  zaychik:
    image: eclipse-temurin:17-alpine
    container_name: zaychik
    restart: unless-stopped
    volumes:
      - ".:/app"
    command: ['java', '-XX:+UseZGC', '-Xmx512M', '-jar', '/app/zaychik.jar']
