name: Build and Publish

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  build:
    if: (!contains(github.event.head_commit.message, 'no build'))

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
    
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    
    - name: Build with Gradle
      run: ./gradlew shadowJar
    
    - name: Publish release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          **/*/zaychik-all.jar
          **/*/zaychik.jar
          docker-compose.yml
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
